### ISSUE TITLE
Can't generate spectros - Matplotlib version conflict

### ISSUE THREAD

**Issue by PaulCarvaillo** [Project-OSmOSE/OSEkit#156]
Context:

Using OSmOSE installed from .whl file version 0.2.0. 

Build and initialize methods worked fine on my dataset.

After calling .process_all_files() method I get this error:

> `---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[6], [line 3](vscode-notebook-cell:?execution_count=6&line=3)
>       [1](vscode-notebook-cell:?execution_count=6&line=1) print(spectrogram)
>       [2](vscode-notebook-cell:?execution_count=6&line=2) print(spectrogram.check_spectro_size())
> ----> [3](vscode-notebook-cell:?execution_count=6&line=3) previz_spectrogram(spectrogram=spectrogram,number_of_previz=5)
> 
> Cell In[1], [line 41](vscode-notebook-cell:?execution_count=1&line=41)
>      [39](vscode-notebook-cell:?execution_count=1&line=39) # Process the reshaped file
>      [40](vscode-notebook-cell:?execution_count=1&line=40) for audio_file in random.sample(files_adjust,number_of_previz):
> ---> [41](vscode-notebook-cell:?execution_count=1&line=41)     spectrogram.process_file(audio_file, adjust=True)
>      [43](vscode-notebook-cell:?execution_count=1&line=43) # Save the spectrogram metadata
>      [44](vscode-notebook-cell:?execution_count=1&line=44) spectrogram.save_spectro_metadata(True)
> 
> File /mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1200, in Spectrogram.process_file(self, audio_file, adjust, save_matrix, save_for_LTAS, overwrite, clean_adjust_folder)
>    [1197](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1197) data = signal.sosfilt(bpcoef, data)
>    [1199](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1199) print(f"Generating spectrograms for {output_file.name}")
> -> [1200](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1200) self.gen_tiles(data=data, sample_rate=sample_rate, output_file=output_file, adjust=adjust)
> 
> File /mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1303, in Spectrogram.gen_tiles(self, data, sample_rate, output_file, adjust)
>    [1300](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1300)         if self.spectro_normalization == "spectrum":
>    [1301](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1301)             log_spectro = 10 * np.log10(Sxx_int)
> -> [1303](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1303)         self.generate_and_save_figures(
>    [1304](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1304)             time=segment_times_int,
>    [1305](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1305)             freq=Freq,
>    [1306](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1306)             log_spectro=log_spectro,
>    [1307](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1307)             output_file=output_file.parent.joinpath(
>    [1308](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1308)                 f"{output_file.stem}_{str(2 ** zoom_level)}_{str(tile)}.png"
>    [1309](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1309)             ),
>    [1310](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1310)             adjust=adjust
>    [1311](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1311)         )
>    [1314](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1314) # highest tuile resolution
>    [1315](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1315) if False:
> 
> File /mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1457, in Spectrogram.generate_and_save_figures(self, time, freq, log_spectro, output_file, adjust)
>    [1448](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1448) fig, ax = plt.subplots(
>    [1449](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1449)     nrows=1,
>    [1450](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1450)     ncols=1,
>    [1451](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1451)     figsize=(fact_x * 1800 / my_dpi, fact_y * 512 / my_dpi),
>    [1452](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1452)     dpi=my_dpi,
>    [1453](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1453) )
>    [1455](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1455) print(f"- min log spectro : {np.amin(log_spectro)} \n - max log spectro : {np.amax(log_spectro)} \n")
> -> [1457](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1457) color_map = cm.get_cmap(self.colormap)  # .reversed()
>    [1458](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1458) plt.pcolormesh(time, freq, log_spectro, cmap=color_map)
>    [1459](https://vscode-remote+ssh-002dremote-002b10-002e12-002e91-002e18.vscode-resource.vscode-cdn.net/mnt/Data/Tools/anaconda3/envs/mmermaid-env/lib/python3.10/site-packages/OSmOSE/Spectrogram.py:1459) plt.clim(vmin=self.dynamic_min, vmax=self.dynamic_max)
> 
> AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'`

This comes from matplotlib version ==> pip install --force-reinstall matplotlib==3.7.0 fixed the problem.

They changed colormap attributes. 

Version 3.7.0 -the one osekit is currently using-:
https://matplotlib.org/3.7.0/api/_as_gen/matplotlib.pyplot.get_cmap.html

Current version 3.9.0 (stable):
https://matplotlib.org/stable/api/cm_api.html

I think the
 ```
from matplotlib import pyplot as plt
...
plt.cm.get_cmap('viridis')`
``` 
is deprecated.

and we should use:
```
`import matplotlib.pyplot as plt
import matplotlib.colormaps as cm

cm.get_cmap('Viridis')`

```

in pyproject.toml I see this:
`
matplotlib = "^3.7.0"`

With this description, it installed 3.9.0 by default in our environment.

Can we update code to work with matplotlib 3.9.0 ? 
otherwise we can freeze the version with `matplotlib==3.7.0. `in pyproject.toml
